version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:latest
    container_name: autotfc
    volumes:
      - <HOST_MACHINE_FOLDER>/autotfc/data:/data
    environment:
      EULA: "true"
      TYPE: FORGE
      VERSION: 1.18.2
      FORGE_VERSION: 40.2.1
    ports:
      - "25565:25565"
    restart: unless-stopped

volumes:
  data: {}
